version: '3'
services:
  db:
    build:
      context: ./db
    image: hackfterword-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    image: hackfterwork-api
    environment:
      - DB_USER=docker
      - DB_PASS=docker
      - DB_SCHEMA=docker
      - DB_HOST=db
    ports:
      - "3000:3000"
    command: bash -c "sleep 10 && npm start"


volumes:
  db-data: